### ISSUE TITLE
Instabot giving 400

### ISSUE THREAD

**Issue by ApoorvTyagi** [suryashekharc/insta_reddit#1]
Looks like Instagram has done some changes in their API because of which instabot is failing to upload photos. Getting this -  
ERROR - Photo Upload failed with the following response: <Response [400]>

**Comment by ApoorvTyagi** [comment]
I think the issue is with .png files

**Comment by suryashekharc** [comment]
Great catch Apoorv! I faced this issue since the image generated is a PNG by default but Instabot expects a JPG.
Check [this line](https://github.com/suryashekharc/insta_reddit/blob/a22ab87a2d4c1a81b924c9869d646769d6dedbab/insta_reddit/code/image_utils.py#L23) to see how I had taken care of it. The error should go away.

Instabot uploading seems to work fine otherwise :) 
Closing this issue, but do feel free to open in case this doesn't work out. And thank you for giving this a spin!
